### PR TITLE
Image Cartoonizer

### PR DESCRIPTION
**Pull request by ibradzm**

### CODE REVIEW

**Comment by Kunal-Garg-12** [comment]
@ibradzm When I check this PR on my local system all I get is an empty directory. Please check your PR

**Comment by ibradzm** [comment]
I fixed it, take a moment and check again

**Comment by Kunal-Garg-12** [comment]
@ibradzm Please add a ReadME.md file detailing about steps to run this because it is very confusing for beginners to even install this otherwise. I will merge the PR once this is done

**Comment by ibradzm** [comment]
I've added requirements.txt which has all libraries to run the program
And I've also added RedME.md which has the steps to use it as you mentioned

**Comment by Kunal-Garg-12** [comment]
Great @ibradzm

**Pull request merged**
